#pragma once
#include "./bit_writer.h"
#include "./common_function.h"
#include "./config_parser.h"
#include "./file_helper.h"
#include "./log_writer.h"
#include "./string_helper.hpp"
#include <iostream>
#include <stdio.h>
